package yukta;

public class TryCatchFinallyExample {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		int result=10/0;
		System.out.println("Result "+result);
		}
		catch(ArithmeticException e){
			System.out.println("An error occured "+e.getMessage());
		}
		finally {
			System.out.println("Finally block executed");
		}
	}
	

}
